### ISSUE TITLE
can u show us more examples for using this extension?

### ISSUE THREAD

**Issue by jhp2060** [roeniss/decodeURLbyClick-extension#1]
actually i cannot understand how this works well. i just want u to show us more examples about how to use it 😊

**Comment by roeniss** [comment]
Hi @jhp2060, first thank you so much for leaving issue on my repo!

Let me give you a little detailed example: 

0) I hope you use latest chrome browser for below steps :)

1) Click this link : [velog.io/@roeniss/%ED%81%AC%EB%A1%AC-%ED%99%95%EC%9E%A5-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%A8%EC%9D%84-%EB%A7%8C%EB%93%A4%EC%96%B4%EB%B3%B4%EC%95%98%EB%8B%A4](https://velog.io/@roeniss/%ED%81%AC%EB%A1%AC-%ED%99%95%EC%9E%A5-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%A8%EC%9D%84-%EB%A7%8C%EB%93%A4%EC%96%B4%EB%B3%B4%EC%95%98%EB%8B%A4)

2) You can see that url is not the same with what you click, which is [velog.io/@roeniss/크롬-확장-프로그램을-만들어보았다](https://velog.io/@roeniss/크롬-확장-프로그램을-만들어보았다)

(you may or may not see scheme('https://') in front of the url but that's not the point so ignore it please)

3) Try to click the url and copy it. When you paste it, you will see the percent-encoded url which is the same with step 1's.

4) Now, click the app icon after download it. You can find it on browser's top left corner. If you can't, click puzzle icon. 

5) When you click it, you will see that the icon color turns to red, which was green. It means your copied url in clipboard is decoded well.

6) Paste it like step 3. Now you will get the decoded url which is the same with step 2's! That's what the app does 💯

**Comment by roeniss** [comment]
If above instruction is not satisfying, please let me know the pain point with reopen.
